phone: 123 456 789
email: email@email.com

titles:
  features: Fabric is More than a LMS
  companies: Fabric is Helping
  case_studies: Our Case Studies
  about: Learn About Cogcentric Labs
  demo: Watch Fabric in Action
  contact: Get Started With Fabric

tagline: The most advanced learning management software in the world.

text:
  about: |
    Cogcentric Labs develops educational software, including the learning management system onFabric, and provide organizations with instructional design solutions.

    onFabric is the leading online learning platform for a new era in education and business. We add value through its unmatched flexibility, affordable price, and our commitment to empowering customers. We tailor onFabric to meet the individual needs of each customer, and, quite simply, it can do things that others can't.

  contact: contact us about fabric!
  demo: Watch this video

people:
  - name: Seth Tee
    position: Co-founder and CTO
    image: /img/people/seth.gif
    tagline: Educational technology researcher, software developer, musician and game designer. Seth wrote the core code for Fabric and leads development efforts.

  - name: Ken MacAllister
    position: Co-founder and CEO
    image: /img/people/ken.gif
    tagline: Educational technology researcher, teacher, instructional designer and consultant. Ken built the business model around Fabric and manages operations.

  - name: Adam Creelman
    position: Business Development Manager
    image: /img/people/adam.gif
    tagline: Educational technology researcher, business grad and expert in communities of practice. Adam is making our business more scalable.